theme = "catppuccin_mocha"

[editor]
mouse = false
shell = ["nu", "-c"]
line-number = "absolute"
cursorline = true
cursorcolumn = false
auto-completion = true
auto-format = true
auto-save = false
completion-timeout = 500
completion-trigger-len = 4
completion-replace = true
auto-info = true
text-width = 120
workspace-lsp-roots = []
default-line-ending = "lf"
# popup-border = "all"
indent-heuristic = "hybrid" # might switch to "tree-sitter" depending on lang

[editor.statusline]
left = ["mode", "version-control", "spinner"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-type","file-encoding"]
separator = "|"
mode.normal = "CMD"
mode.insert = "INS"
mode.select = "SEL"

[editor.cursor-shape]
normal = "underline"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = true

#[editor.auto-pairs]
# should be set per-language and not here

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
newline = "⏎"

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.soft-wrap]
enable = false

[editor.smart-tab]
enable = false
